name: Bug Hunters

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Build
      working-directory: ./bug-hunters
      run: |
        npm install

    - name: Test
      working-directory: ./bug-hunters
      run: |
        npm run test -- --verbose
